
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8089
  servlet:
    # 应用的访问路径
    context-path: /api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    max-http-header-size: 10240000
# Spring配置
spring:
    #es
  elasticsearch:
    rest:
      uris: 172.100.3.3:9200

